#!/bin/bash
CURRENT=$(cd $(dirname $0) && pwd)
source $CURRENT/common.sh

TMPFILE=`mktemp`
cat > $TMPFILE <<EOT
<?php
  /* AUTO GENERATED BY bin/update_constants.sh */
  define('JITSUI_IP', '${JITSUI_IP}');
  define('DB_USER', '${DB_USER}');
  define('DB_PASSWORD', '${DB_PASSWORD}');
  define('DB_TEST', '${DB_TEST}');
EOT

file_development=$INSTALL_DIR/development/app/Config/constants.php
file_production=$INSTALL_DIR/production/app/Config/constants.php
rm -f $file_development $file_production
cp $TMPFILE $file_development
cp $TMPFILE $file_production
rm $TMPFILE

echo "  define('TIE_RUN_MODE', 'development');"   >> $file_development
echo "  define('DB_NAME', '${DB_DEVELOPMENT}');"  >> $file_development
echo "  define('DEBUG_TODAY', '${DEBUG_TODAY}');" >> $file_development
echo "  define('TIE_RUN_MODE', 'production');" >> $file_production
echo "  define('DB_NAME', '${DB_PRODUCTION}');"  >> $file_production

chmod 666 $file_development
chmod 666 $file_production
